apiVersion: v1
kind: Pod
metadata:
  name: nginx-nfs
  namespace: default
spec:
  nodeName: "kubernetes-minion-group-7bw3"
  containers:
  - name: nginx-nfs
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "nfs"
      fsType: "nfs"
      options:
        server: "10.244.3.6"
        share: "exports"
